# Generated by Django 3.0.8 on 2020-09-08 09:42

from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200901_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('GBP', 'GBP £'), ('HUF', 'HUF Ft'), ('USD', 'USD $')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('GBP', 'GBP £'), ('HUF', 'HUF Ft'), ('USD', 'USD $')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=4, max_digits=19, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=4, max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
    ]
