# Generated by Django 3.0.8 on 2020-09-08 11:41

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200908_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_currency',
        ),
        migrations.AddField(
            model_name='product',
            name='min_price',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=19, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='min_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('GBP', 'GBP £'), ('HUF', 'HUF Ft'), ('USD', 'USD $')], default='HUF', editable=False, max_length=3),
        ),
    ]
