# Generated by Django 3.0.8 on 2020-09-22 13:57

from decimal import Decimal
import django.core.validators
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200916_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
